name: Docker build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build SPA
      run: |
        ls
        docker build -t base-react-app .
    - name: Build docker-compose
      run: |
        docker-compose up --build -d
